### ISSUE TITLE
git recursive clone missing

### ISSUE THREAD

**Issue by amdshameer** [stephane-caron/pymanoid#15]
git recursive clone is missing in the [README](https://github.com/stephane-caron/pymanoid/blob/master/README.md). Due to that, "pypoman" and "qpsolvers" are not cloned as a part of gitmodules
`
$ git clone --recursive https://github.com/stephane-caron/pymanoid.git
`
@stephane-caron

**Comment by stephane-caron** [comment]
Fixed by b2b36c2. Thanks!
