### ISSUE TITLE
Inverse Kinematic code make robot fall down

### ISSUE THREAD

**Issue by mohamadmahdavian** [stephane-caron/pymanoid#17]
Hello

I was able to import a simple Solidworks model of a biped robot into pymanoid and I was able to prepare the "Posture generation" code for it and its working properly. Also, I tried to implement "inverse Kinematic" code. But the code is unable to solve the IK for initial position and the robot keeps falling down.I attached a zip file containing iteration of solving IK. I really appreciate it if you could help me for solving this problem.

Thank You
[Iterations.zip](https://github.com/stephane-caron/pymanoid/files/2609046/Iterations.zip)

Best Regards

**Comment by stephane-caron** [comment]
Hi Mohamad,

I just pushed some debug instructions in 890fa119ffee2a780f65e7289dde0f28e2b35f4f. Can you pull the latest version of pymanoid and re-run the ``inverse_kinematics.py`` example?

It will print out additional debug messages (using the ``robot.ik.verbosity`` field) that we can use to take a look at your tasks.

**Comment by mohamadmahdavian** [comment]
Thank You Dr.Caron for your reply. This is the result of the code:

                 COM  2.44e+03
             POSTURE  1.03e+04

45: 1.699e+05 (impr: +6.08e-02)

                TASK      COST
------------------------------
      left_foot_base  2.50e+02
     right_foot_base  1.53e+02
                 COM  2.50e+03
             POSTURE  1.04e+04

46: 1.652e+05 (impr: +2.75e-02)

                TASK      COST
------------------------------
      left_foot_base  2.67e+02
     right_foot_base  1.60e+02
                 COM  2.44e+03
             POSTURE  1.04e+04

47: 1.720e+05 (impr: +4.08e-02)

                TASK      COST
------------------------------
      left_foot_base  2.53e+02
     right_foot_base  1.54e+02
                 COM  2.47e+03
             POSTURE  1.03e+04

48: 1.602e+05 (impr: +6.81e-02)

                TASK      COST
------------------------------
      left_foot_base  2.66e+02
     right_foot_base  1.61e+02
                 COM  2.47e+03
             POSTURE  1.03e+04

49: 1.632e+05 (impr: +1.83e-02)

                TASK      COST
------------------------------
      left_foot_base  2.59e+02
     right_foot_base  1.47e+02
                 COM  2.45e+03
             POSTURE  1.04e+04

50: 1.712e+05 (impr: +4.95e-02)

                TASK      COST
------------------------------
      left_foot_base  2.66e+02
     right_foot_base  2.01e+02
                 COM  2.46e+03
             POSTURE  1.04e+04

51: 1.711e+05 (impr: +7.00e-04)

                TASK      COST
------------------------------
      left_foot_base  2.66e+02
     right_foot_base  2.00e+02
                 COM  2.46e+03
             POSTURE  1.04e+04

52: 1.710e+05 (impr: +6.79e-04)

                TASK      COST
------------------------------
      left_foot_base  2.66e+02
     right_foot_base  2.00e+02
                 COM  2.45e+03
             POSTURE  1.04e+04

53: 1.709e+05 (impr: +6.58e-04)

                TASK      COST
------------------------------
      left_foot_base  2.66e+02
     right_foot_base  1.99e+02
                 COM  2.45e+03
             POSTURE  1.04e+04

54: 1.708e+05 (impr: +6.39e-04)

                TASK      COST
------------------------------
      left_foot_base  2.66e+02
     right_foot_base  1.99e+02
                 COM  2.45e+03
             POSTURE  1.04e+04

55: 1.707e+05 (impr: +6.20e-04)

                TASK      COST
------------------------------
      left_foot_base  2.66e+02
     right_foot_base  1.98e+02
                 COM  2.45e+03
             POSTURE  1.04e+04

56: 1.706e+05 (impr: +6.01e-04)

                TASK      COST
------------------------------
      left_foot_base  2.66e+02
     right_foot_base  1.98e+02
                 COM  2.45e+03
             POSTURE  1.04e+04

57: 1.705e+05 (impr: +5.84e-04)

                TASK      COST
------------------------------
      left_foot_base  2.67e+02
     right_foot_base  1.98e+02
                 COM  2.45e+03
             POSTURE  1.04e+04

58: 1.704e+05 (impr: +5.66e-04)

                TASK      COST
------------------------------
      left_foot_base  2.67e+02
     right_foot_base  1.97e+02
                 COM  2.45e+03
             POSTURE  1.04e+04

59: 1.703e+05 (impr: +5.50e-04)

                TASK      COST
------------------------------
      left_foot_base  2.67e+02
     right_foot_base  1.97e+02
                 COM  2.45e+03
             POSTURE  1.04e+04

60: 1.702e+05 (impr: +5.34e-04)

                TASK      COST
------------------------------
      left_foot_base  2.67e+02
     right_foot_base  1.96e+02
                 COM  2.45e+03
             POSTURE  1.04e+04

61: 1.701e+05 (impr: +5.18e-04)

                TASK      COST
------------------------------
      left_foot_base  2.67e+02
     right_foot_base  1.96e+02
                 COM  2.45e+03
             POSTURE  1.04e+04

62: 1.700e+05 (impr: +5.03e-04)

                TASK      COST
------------------------------
      left_foot_base  2.67e+02
     right_foot_base  1.96e+02
                 COM  2.45e+03
             POSTURE  1.04e+04

63: 1.699e+05 (impr: +4.89e-04)

                TASK      COST
------------------------------
      left_foot_base  2.68e+02
     right_foot_base  1.95e+02
                 COM  2.45e+03
             POSTURE  1.04e+04

64: 1.699e+05 (impr: +4.75e-04)

                TASK      COST
------------------------------
      left_foot_base  2.68e+02
     right_foot_base  1.95e+02
                 COM  2.45e+03
             POSTURE  1.04e+04

65: 1.698e+05 (impr: +4.61e-04)

                TASK      COST
------------------------------
      left_foot_base  2.68e+02
     right_foot_base  1.94e+02
                 COM  2.45e+03
             POSTURE  1.04e+04

66: 1.697e+05 (impr: +4.48e-04)

                TASK      COST
------------------------------
      left_foot_base  2.68e+02
     right_foot_base  1.94e+02
                 COM  2.45e+03
             POSTURE  1.04e+04

67: 1.696e+05 (impr: +4.35e-04)

                TASK      COST
------------------------------
      left_foot_base  2.68e+02
     right_foot_base  1.94e+02
                 COM  2.45e+03
             POSTURE  1.03e+04

68: 1.696e+05 (impr: +4.23e-04)

                TASK      COST
------------------------------
      left_foot_base  2.68e+02
     right_foot_base  1.93e+02
                 COM  2.45e+03
             POSTURE  1.03e+04

69: 1.695e+05 (impr: +4.11e-04)

                TASK      COST
------------------------------
      left_foot_base  2.68e+02
     right_foot_base  1.93e+02
                 COM  2.45e+03
             POSTURE  1.03e+04

70: 1.694e+05 (impr: +4.00e-04)

                TASK      COST
------------------------------
      left_foot_base  2.69e+02
     right_foot_base  1.93e+02
                 COM  2.45e+03
             POSTURE  1.03e+04

71: 1.694e+05 (impr: +3.89e-04)

                TASK      COST
------------------------------
      left_foot_base  2.69e+02
     right_foot_base  1.92e+02
                 COM  2.45e+03
             POSTURE  1.03e+04

72: 1.693e+05 (impr: +3.78e-04)

                TASK      COST
------------------------------
      left_foot_base  2.69e+02
     right_foot_base  1.92e+02
                 COM  2.45e+03
             POSTURE  1.03e+04

73: 1.692e+05 (impr: +3.68e-04)

                TASK      COST
------------------------------
      left_foot_base  2.69e+02
     right_foot_base  1.92e+02
                 COM  2.45e+03
             POSTURE  1.03e+04

74: 1.692e+05 (impr: +3.57e-04)

                TASK      COST
------------------------------
      left_foot_base  2.69e+02
     right_foot_base  1.92e+02
                 COM  2.45e+03
             POSTURE  1.03e+04

75: 1.691e+05 (impr: +3.48e-04)

                TASK      COST
------------------------------
      left_foot_base  2.69e+02
     right_foot_base  1.91e+02
                 COM  2.45e+03
             POSTURE  1.03e+04

76: 1.691e+05 (impr: +3.38e-04)

                TASK      COST
------------------------------
      left_foot_base  2.69e+02
     right_foot_base  1.91e+02
                 COM  2.45e+03
             POSTURE  1.03e+04

77: 1.690e+05 (impr: +3.29e-04)

                TASK      COST
------------------------------
      left_foot_base  2.70e+02
     right_foot_base  1.91e+02
                 COM  2.45e+03
             POSTURE  1.03e+04

78: 1.689e+05 (impr: +3.20e-04)

                TASK      COST
------------------------------
      left_foot_base  2.70e+02
     right_foot_base  1.90e+02
                 COM  2.45e+03
             POSTURE  1.03e+04

79: 1.689e+05 (impr: +3.12e-04)

                TASK      COST
------------------------------
      left_foot_base  2.70e+02
     right_foot_base  1.90e+02
                 COM  2.45e+03
             POSTURE  1.03e+04

80: 1.688e+05 (impr: +3.04e-04)

                TASK      COST
------------------------------
      left_foot_base  2.70e+02
     right_foot_base  1.90e+02
                 COM  2.45e+03
             POSTURE  1.03e+04

81: 1.688e+05 (impr: +2.96e-04)

                TASK      COST
------------------------------
      left_foot_base  2.70e+02
     right_foot_base  1.89e+02
                 COM  2.45e+03
             POSTURE  1.03e+04

82: 1.687e+05 (impr: +2.88e-04)

                TASK      COST
------------------------------
      left_foot_base  2.70e+02
     right_foot_base  1.89e+02
                 COM  2.44e+03
             POSTURE  1.03e+04

83: 1.687e+05 (impr: +2.81e-04)

                TASK      COST
------------------------------
      left_foot_base  2.70e+02
     right_foot_base  1.89e+02
                 COM  2.44e+03
             POSTURE  1.03e+04

84: 1.687e+05 (impr: +2.73e-04)

                TASK      COST
------------------------------
      left_foot_base  2.70e+02
     right_foot_base  1.89e+02
                 COM  2.44e+03
             POSTURE  1.03e+04

85: 1.686e+05 (impr: +2.66e-04)

                TASK      COST
------------------------------
      left_foot_base  2.71e+02
     right_foot_base  1.88e+02
                 COM  2.44e+03
             POSTURE  1.03e+04

86: 1.686e+05 (impr: +2.60e-04)

                TASK      COST
------------------------------
      left_foot_base  2.71e+02
     right_foot_base  1.88e+02
                 COM  2.44e+03
             POSTURE  1.03e+04

87: 1.685e+05 (impr: +2.53e-04)

                TASK      COST
------------------------------
      left_foot_base  2.71e+02
     right_foot_base  1.88e+02
                 COM  2.44e+03
             POSTURE  1.03e+04

88: 1.685e+05 (impr: +2.47e-04)

                TASK      COST
------------------------------
      left_foot_base  2.71e+02
     right_foot_base  1.88e+02
                 COM  2.44e+03
             POSTURE  1.03e+04

89: 1.684e+05 (impr: +2.41e-04)

                TASK      COST
------------------------------
      left_foot_base  2.71e+02
     right_foot_base  1.87e+02
                 COM  2.44e+03
             POSTURE  1.03e+04

90: 1.684e+05 (impr: +2.35e-04)

                TASK      COST
------------------------------
      left_foot_base  2.71e+02
     right_foot_base  1.87e+02
                 COM  2.44e+03
             POSTURE  1.03e+04

91: 1.684e+05 (impr: +2.29e-04)

                TASK      COST
------------------------------
      left_foot_base  2.71e+02
     right_foot_base  1.87e+02
                 COM  2.44e+03
             POSTURE  1.03e+04

92: 1.683e+05 (impr: +2.23e-04)

                TASK      COST
------------------------------
      left_foot_base  2.71e+02
     right_foot_base  1.87e+02
                 COM  2.44e+03
             POSTURE  1.03e+04

93: 1.683e+05 (impr: +2.18e-04)

                TASK      COST
------------------------------
      left_foot_base  2.72e+02
     right_foot_base  1.86e+02
                 COM  2.44e+03
             POSTURE  1.03e+04

94: 1.683e+05 (impr: +2.13e-04)

                TASK      COST
------------------------------
      left_foot_base  2.72e+02
     right_foot_base  1.86e+02
                 COM  2.44e+03
             POSTURE  1.03e+04

95: 1.682e+05 (impr: +2.08e-04)

                TASK      COST
------------------------------
      left_foot_base  2.72e+02
     right_foot_base  1.86e+02
                 COM  2.44e+03
             POSTURE  1.03e+04

96: 1.682e+05 (impr: +2.03e-04)

                TASK      COST
------------------------------
      left_foot_base  2.72e+02
     right_foot_base  1.86e+02
                 COM  2.44e+03
             POSTURE  1.03e+04

97: 1.681e+05 (impr: +1.98e-04)

                TASK      COST
------------------------------
      left_foot_base  2.72e+02
     right_foot_base  1.86e+02
                 COM  2.44e+03
             POSTURE  1.03e+04

98: 1.681e+05 (impr: +1.93e-04)

                TASK      COST
------------------------------
      left_foot_base  2.72e+02
     right_foot_base  1.85e+02
                 COM  2.44e+03
             POSTURE  1.03e+04

99: 1.681e+05 (impr: +1.89e-04)

                TASK      COST
------------------------------
      left_foot_base  2.72e+02
     right_foot_base  1.85e+02
                 COM  2.44e+03
             POSTURE  1.03e+04

**Comment by stephane-caron** [comment]
Hmm, your initial costs are very large. This could come from an invalid initial ``robot.q`` before the call to ``robot.ik.solve()``, which was indeed a difference between the IK and PG examples. 

Can you pull the latest master now and try again?

**Comment by mohamadmahdavian** [comment]
Hi Dr.Caron

Thank you for updating the code. Actually, I found the main reason for that problem. It is necessary that coordinate defined on foot placement position and coordinate of each foot is in same direction. Other than that it will try to converge to something wrong. The problem is I can't rotate the foot placement point in X and Y direction for 180 degrees. Because it gives me this error:

  File "<ipython-input-1-fadaa44fc77d>", line 1, in <module>
    runfile('/home/mohammad/catkin_ws/pymanoid/pymanoid/examples/Straight_walk_for_simple_robot.py', wdir='/home/mohammad/catkin_ws/pymanoid/pymanoid/examples')

  File "/usr/lib/python2.7/dist-packages/spyderlib/widgets/externalshell/sitecustomize.py", line 699, in runfile
    execfile(filename, namespace)

  File "/usr/lib/python2.7/dist-packages/spyderlib/widgets/externalshell/sitecustomize.py", line 81, in execfile
    builtins.execfile(filename, *where)

  File "/home/mohammad/catkin_ws/pymanoid/pymanoid/examples/Straight_walk_for_simple_robot.py", line 872, in <module>
    init_com_offset=array([0., 0., 0.]))

  File "/home/mohammad/catkin_ws/pymanoid/pymanoid/examples/Straight_walk_for_simple_robot.py", line 131, in generate_staircase
    dsr_stance.compute_static_equilibrium_polygon()

  File "/home/mohammad/.local/lib/python2.7/site-packages/pymanoid/stance.py", line 207, in compute_static_equilibrium_polygon
    method=method)

  File "/home/mohammad/.local/lib/python2.7/site-packages/pymanoid/contact.py", line 321, in compute_static_equilibrium_polygon
    return compute_polygon_hull(B, c)

  File "/home/mohammad/.local/lib/python2.7/site-packages/pymanoid/pypoman/pypoman/polygon.py", line 120, in compute_polygon_hull
    x = compute_chebyshev_center(B, c)

  File "/home/mohammad/.local/lib/python2.7/site-packages/pymanoid/pypoman/pypoman/polyhedron.py", line 68, in compute_chebyshev_center
    z = solve_lp(cost, A_cheby, b)

  File "/home/mohammad/.local/lib/python2.7/site-packages/pymanoid/pypoman/pypoman/lp.py", line 97, in solve_lp
    raise ValueError("LP optimum not found: %s" % sol['status'])

ValueError: LP optimum not found: dual infeasible


Do you know how can I fix it?

**Comment by stephane-caron** [comment]
This error most likely means that your contact set is invalid. If you rotate a contact 180 degrees around its X and Y axes, it will end up pointing down, while other components (here the computation of the static-equilibrium polygon) assume that contact normals point upward.

In your case, I would advise you rotate the manipulator frames of your robot model rather than those of the contact frames. For example, if your robot model is defined in a ``.dae`` file, manipulator frames look like this:
```
    <extra name="left_hand_palm" type="manipulator">
        <technique profile="OpenRAVE">
            <frame_origin link="kmodel1/link0"/>
            <frame_tip link="kmodel1/link38">
                <translate>0 -0.005 -0.1</translate>
                <rotate>1 0 0 90</rotate>
                <rotate>0 0 1 -90</rotate>
            </frame_tip>
        </technique>
    </extra>
```
You can stack up ``<rotate>`` directives as in the example above to rotate your manipulator frame locally.

**Comment by stephane-caron** [comment]
To follow-up on this:

![image](https://user-images.githubusercontent.com/1189580/50403736-7379c500-07a1-11e9-93db-aa572f5af48c.png)

Here the ``left_foot_base`` and ``right_foot_base`` manipulator frames are not pointing in the proper directions.

- The x-axis (red arrow) should be pointing forward (from heel to toe of foot)
- The y-axis (green arrow) should be pointing to the left (from right to left of foot)
- The z-axis (blue arrow) should be pointing upward

Manipulator frames are oriented this way in the [JVRC-1](https://github.com/stephane-caron/openrave_models/tree/master/JVRC-1) model for instance. In the picture above, ``right_foot_base`` should be rotate 180 degrees around its present z-axis, while ``left_foot_base`` should be rotated 180 degrees around its present y-axis.
