### ISSUE TITLE
Log data (pos. & orient. of each point), free-flyer point, JVRC robot geometry info

### ISSUE THREAD

**Issue by Ahmadreza-Shahrokhshahi** [stephane-caron/pymanoid#18]
Hi Dr. Caron,
For a certain simulation, we wanted to have some results form the Pymanoid simulation such as: the joint angles (q), the ground reaction forces, the CoP position relative to each foot-plate during the motion (where the forces are applied), position and orientation of an arbitrary point on the robot body (I considered the free-flyer point because it is easy to have access). I can have access to these values, but there are still a question:

Where is exactly the free-flyer point attached to the waist body (I want to know the exact definition for the free-flyer point)

It would be appreciated if I could hear from you at your earliest convenience.
Thanks

**Comment by Ahmadreza-Shahrokhshahi** [comment]
Thanks for your response. My other problem which I also mentioned in the topic is that I want to log position and orientation of an arbitrary point on the robot body such as the point correspond to the hip joint. I would be grateful if I could know about it.

Thank you

**Comment by stephane-caron** [comment]
OK, for this you need to dig into the robot links. Here is an example when ``robot`` is JVRC-1:
```python
right_hip_link = pymanoid.body.Body(robot.rave.GetLink('R_HIP_P_S'))
right_hip_link.R  # body orientation in world frame
right_hip_link.p  # body position in world frame
```
Link names are those of your COLLADA files, you can see all of them in ``robot.rave.GetLinks()``. Note that you can also see the link name to the top-left of the OpenRAVE viewer when your mouse hovers it in edit mode. For instance, in the screenshot below my mouse was over L_HIP_Y_S:

![image](https://user-images.githubusercontent.com/1189580/51208471-155a8080-190e-11e9-9f3c-a8c4760a2605.png)

**Comment by stephane-caron** [comment]
I added the `Robot.get_link` function to ease this process. Now one can do:
```python
In [1]: right_hip_link = robot.get_link("R_HIP_P_S")

In [2]: right_hip_link.R
Out[2]: 
array([[  9.08398477e-01,   2.54259930e-03,  -4.18097765e-01],
       [ -3.01809711e-04,   9.99985236e-01,   5.42552118e-03],
       [  4.18105388e-01,  -4.80234922e-03,   9.08385833e-01]])
```
