### ISSUE TITLE
build error with pymanoid.task

### ISSUE THREAD

**Issue by LinYuChi** [stephane-caron/pymanoid#2]
Hi Stéphane,

I found that "python setup.py" does not work. Here is the error message:

```yuchi@yuchi-OptiPlex-7040:~/pymanoid$ python setup.py build
running build
running build_py
error: package directory 'pymanoid/tasks' does not exist
```

It seems simply deleting the 'pymanoid.tasks' in the packages list in setup.py will solve the problem, and I can still see tasks.py(I guess it is the thing 'pymanoid.tasks' tried to build) in the build directory.

Yu-Chi

**Comment by stephane-caron** [comment]
Just fixed this, thanks :)
