### ISSUE TITLE
Walking Robot Gets Unbalanced

### ISSUE THREAD

**Issue by mohamadmahdavian** [stephane-caron/pymanoid#21]
Hello Dr.Caron

I hope you are doing well. As you know I have imported my robot's model and generated walking motion for the robot. But over the time the robot is tilting backward and it gets unbalanced. The legs walking is happening based on the specified time, but I think COM can't follow the goal for the COM properly. I attached some photos for you to show it better. Do you know what might be the reason for it? 

Thank You
Regards
[Walking Photos.zip](https://github.com/stephane-caron/pymanoid/files/2822948/Walking.Photos.zip)

**Comment by mohamadmahdavian** [comment]
Hello Dr.Caron

I hope you are well. I recorded a video from our robot motion while walking in pymanoid to show you the motion better. As you can see in the video, robot body leans backward and gets unbalanced over the time. I tried to change some variables in the code to make it balanced, but I was unsuccessful. I wanted to know if you had the same problem with your robot or not? or if you have any idea for fixing this problem. Because, the same problem happened to me while importing all of our robot models and there should be some way for fixing it. If it's a fundamental problem which has been addressed in your papers, please tell me. So we would check the relevant part and if it's only a coding problem which can be fixed easier please inform me as well. 

Thank You again for your help and support
Warm Regards

[Walking Motion.zip](https://github.com/stephane-caron/pymanoid/files/2842234/Walking.Motion.zip)
[Motion Gets Unbalanced.zip](https://github.com/stephane-caron/pymanoid/files/2842236/Motion.Gets.Unbalanced.zip)

**Comment by mohamadmahdavian** [comment]
Hi Dr.Caron

I need to inform you that the problem of walking robot leaning backward was a mistake in the mass distribution in the collada file and I was able to solve that problem. But whenever I try to walk straight with our robot or even JVRC robot in pymanoid, the robots get unbalanced after around 30 steps. I think it happens due to accumulation of small errors. But it doesn't happen in multi_contact_walking code which is strange. Because the walking condition is harder in second case. I am trying to figure out the reason and I just wanted to inform you about this problem to share with me any ideas about the possible reasons.

Thank You
Warm Regards

**Comment by stephane-caron** [comment]
OK, if the problem is reproducible with JVRC, can you share a minimal script that makes it happen?

In the `multi_contact_walking.py` example it can walk basically forever, so the difference must come from some other difference.

**Comment by mohamadmahdavian** [comment]
Hi Dr.Caron

You are right about "multi_contact_walking.py" code. It won't get unbalanced. But I added following lines to make it walk in straight path and after around 25 to 30 steps it can not walk anymore.

I changed lines 81 to 97 with the following code:

    rfootpose=[0,0]
    lfootpose=[0,0.2]
    
    for cs in range(1,50):
        print(cs)
        rfootpose.append(0.4*cs)
        lfootpose.append(0.4*cs+0.2)
        
    len(rfootpose)
    for xx in range(0,len(rfootpose)-1):
        left_foot = Contact(
            shape=contact_shape,
            pos=[0,
                 rfootpose[xx],
                 0],
            rpy=(roughness * (random(3) - 0.5) + [0, 0, 0 + .5 * pi]),
            friction=friction)
        if first_left_foot is None:
            first_left_foot = left_foot
        right_foot = Contact(
            shape=contact_shape,
            pos=[0.2,
                 lfootpose[xx],
                 0],
            rpy=(roughness * (random(3) - 0.5) + [0, 0, 0 + .5 * pi]),
            friction=friction)


Also changed lines 857 to 865 with the following codes:
    staircase = generate_staircase(
        radius=1.4,
        angular_step=0.25,
        height=0,
        roughness=0,
        friction=0.7,
        ds_duration=0.7,
        ss_duration=1.0,
        init_com_offset=array([0., 0., 0.]))

Also I attached my code and a video for your convenience.

Thank You
Mohammad

[Straight_walk.py.tar.gz](https://github.com/stephane-caron/pymanoid/files/2927635/Straight_walk.py.tar.gz)

[straight_walking_video.mp4.tar.gz](https://github.com/stephane-caron/pymanoid/files/2927651/straight_walking_video.mp4.tar.gz)

**Comment by stephane-caron** [comment]
Interesting! As we can see in the video, the walking goes fine until the robot hits a kind of "invisible wall" and refuses to go forward.

This invisible wall was actually the default joint limit for the "TRANS_Y" joint, set by OpenRAVE to ``10 [m]``. I've updated it to ``10,000 [m]`` so that you have more room to walk :wink: See the corresponding commit if you want to change that in the future.

Once the DOF limit is lifted the robot completes your contact sequence:

![walk_straight](https://user-images.githubusercontent.com/1189580/56271289-7144c900-60f8-11e9-9043-e10b5ab016b9.png)

**Comment by mohamadmahdavian** [comment]
Thank You Dr.Caron
