### ISSUE TITLE
Real robot

### ISSUE THREAD

**Issue by fshamshirdar** [stephane-caron/pymanoid#23]
Hi,

I am trying to run Pymanoid on a real robot. Do you have any suggestion on this? I've seen openrave projects running on both simulator and real robot: https://github.com/roboticsleeds/ur5controller. But here rave is used more often and seems inseparable.

Thanks

**Comment by stephane-caron** [comment]
No particular suggestion here. Your Pymanoid simulation will produce desired targets (e.g. joint angles) at every simulation tick. What's left for you as a user is to write the interface to send these targets to your robot, for instance publishing to the proper topics if your robot is controlled via ROS.

**Comment by fshamshirdar** [comment]
I have applied joint positions to an actual motor (spec: 2300rpm, Maxon driver epos4) with the 30Hz rate but it fails at repeating the trajectory. Continuous tiny shakings in the trajectory (e.g. knee joint in degree: 29.91, 30.01, 29.95, 30.10, 28.90) resulted in motor instability and failure. I assume that is the high acceleration caused by tiny fluctuations.

I was just wondering if you have faced similar issue once you have tested the trajectory in your real robot and if so did you apply any filters on the output and any other solution (IK limit on acceleration) to resolve this?

**Comment by stephane-caron** [comment]
I didn't have this problem with HRP-4, where tiny fluctuations like those you describe are OK. The [StateHolder](https://github.com/fkanehiro/hrpsys-base/tree/master/rtc/StateHolder) component of the HRP system relays commanded joint angles _as is_, so on the software side there is no filtering.

The hardware side (motor driver cards) is another story though. At least, the P and D gains of your motor current controller yield low-pass filtering in themselves. Maybe you want to try different gains to see if it helps in your case. (And if you have an I gain, set it to zero for starters.)

On the pymanoid side, you can add IK acceleration limits as shown in the [inverse_kinematics_tasks.py](https://github.com/stephane-caron/pymanoid/blob/master/examples/inverse_kinematics_tasks.py) example. But again I didn't need to do that in practice.
