### ISSUE TITLE
Getting Sensor data in Pymanoid

### ISSUE THREAD

**Issue by mohamadmahdavian** [stephane-caron/pymanoid#24]
Hello Dr.Caron

I hope you are doing well. I would like to get IMU and foot sensor data in pymanoid while the robot is walking. I have implemented the sensors in the .dae file, but I couldn't find any part of the code which has capability of reading sensor's data from openrave and currently you are calculating the ground reaction forces based on motion of the robot.Do you have any sample code for sensor implementation in pymanoid?

Thank You
M.Mahdavian

**Comment by stephane-caron** [comment]
OpenRAVE sensors are a feature I have not used so far (for IMU and force sensor data I usually manipulate the transform/wrench readings directly in pymanoid), but these sensors can be accessed via ``self.rave.GetSensors()`` on your robot instance. Ask any question related to those on the [OpenRAVE issue tracker](https://github.com/rdiankov/openrave/issues) (more active) or on the [OpenRAVE Users List](http://openrave-users-list.185357.n3.nabble.com/).
