### ISSUE TITLE
Running new version of pymanoid with other 'dt's

### ISSUE THREAD

**Issue by mohamadmahdavian** [stephane-caron/pymanoid#27]
Hello Dr.Caron

I checked out your new version of pymanoid and the updates and I implemented our robot model in it to have a walking motion. I tried to run the code with other 'dt's. But it seems like in dt<0.03 it can not walk with our and your robot model. I was able to generate a good trajectory with dt=0.02 previously and it was working properly. But with new version it doesn't work. I have attached a photo from the com trajectory. Do you have any ideas what the problem is?I think it may be because of MPC controller which generates trajectory of COM.

![Screenshot from 2019-05-07 17-39-19](https://user-images.githubusercontent.com/32945083/57341380-13037880-70ef-11e9-9d60-28dd092bee22.png)

![Screenshot from 2019-05-07 17-25-15](https://user-images.githubusercontent.com/32945083/57341404-26164880-70ef-11e9-9e86-0e9d749fc55b.png)

**Comment by stephane-caron** [comment]
Phase durations are defined from ``dt`` in this script:
```
    ssp_duration = 24 * dt  # 720 [ms]
    dsp_duration = 3 * dt  # 90 [ms]
```
therefore when you reduce ``dt`` it also makes the robot try to walk faster. When phase durations are too small there is no bounded solution and the MPC will diverge.

Note that a well-known solution to avoid all divergence is to add a [boundedness condition](https://www.dis.uniroma1.it/~lanari/Papers/2014%20Humanoids.pdf) to the MPC, _i.e._ a terminal constraint such that the DCM at the end of the preview horizon is located above the last step (in the horizon). However this example is made to illustrate a [tutorial on walking pattern generation](https://scaron.info/teaching/prototyping-a-walking-pattern-generator.html), and I didn't want to go that deep in the implementation for readers new to this topic.

The first thing to do if you want to change ``dt`` in this script is to update all the durations that depend on it (SSP/DSP durations, MPC timestep, etc.)

**Comment by stephane-caron** [comment]
I checked with rounding all durations around ``dt`` in the latest commit. It works fine with _e.g._ ``dt=0.02``, ``dt=0.005`` and ``dt=0.002``.
