### ISSUE TITLE
Camera to visual servoing

### ISSUE THREAD

**Issue by NoePity2** [stephane-caron/pymanoid#28]
Hello Dr.Caron

I hope you are doing well. Is it possible to use a robot camera to make visual servoing control? Do you have any sample code for camera implementation in pymanoid?

Thank You,
Noé Aldana

**Comment by stephane-caron** [comment]
Currently there is no visual servoing example, so you will need to implement the "camera-side" code, _i.e._ reading camera data and extracting a desired camera transform from it. The camera transform is then a target that you can feed to pymanoid's inverse kinematics.

This can be done as [described in this paper](https://hal.inria.fr/hal-01421734/document), resulting in a ``pymanoid.tasks.VisualServoingTask``. I would gladly merge a PR on that if you are interested in implementing it :wink:
