### ISSUE TITLE
Can pymanoid do simulation when external force exerted on hand?

### ISSUE THREAD

**Issue by zhangOSK** [stephane-caron/pymanoid#29]
Dear Stephane,
  How do you do?
  I hope to use pymanoid to do simulation of making humanoid push an object, like a table or box.
  I have a question about simulator that if there is a force sensor at the wrist which can collect information of external force. Besides, is it possible to update the zmp online?
Best
Zhang

**Comment by stephane-caron** [comment]
Hi Zhang,

On a preliminary comment, note that pymanoid performs QP-based inverse dynamics to check [contact stability](https://scaron.info/teaching/contact-stability.html), which differs from a [forward dynamics simulator](https://github.com/stephane-caron/pymanoid/wiki/Frequently-Asked-Questions#does-pymanoid-include-a-forward-dynamics-simulator). 

That being said, you can indeed read the wrenches computed this way in their respective contact frames. For instance, in the ``horizontal_walking.py`` example, you can access them in ``robot.EF_NAME.wrench``:

![2019-06-26-145056_1920x1080_scrot](https://user-images.githubusercontent.com/1189580/60181208-00b9d700-9822-11e9-8d29-bddeb85ccf00.png)

I'm not sure what you mean by "to update the zmp online". One thing that could be possible is to set the CoP/wrench of a given link (for example the hand of the robot pushing an object), then call the QP-based inverse dynamics to find feasible wrenches (if they exist) under the feet or other links in contact. Does that correspond to your use case?

**Comment by zhangOSK** [comment]
Thank you very much for the detailed reply!!! Now I understand how to deal with the wrench stuff.
