### ISSUE TITLE
Inequality constraints under footstep rotations

### ISSUE THREAD

**Issue by Saeed-Mansouri** [stephane-caron/pymanoid#31]
Dear Dr. Caron,

We have opened an issue called [Inequality constraints under footstep rotations](https://github.com/stephane-caron/lipm_walking_controller/issues/9) for the LIPM package. How about the Pymanoid (only horizontal_walking code)? I have found that `T = [R & p \\ 0 & 1]` is a (4×4) affine transformation matrix that goes from the foot frame to the world one. Because `T` is multiplied in vector inequalities, we cannot generally use this formulation to properly calculate the bounds of the ZMP, especially for moving on a curve or turning motion. Is it right?

```python
    def get_scaled_contact_area(self, scale):
        """
        Get the vertices of the scaled contact area.

        Parameters
        ----------
        scale : scalar
            Contact area is scaled by this ratio.

        Returns
        -------
        vertices : list of arrays
            List of vertex coordinates in the world frame.
        """
        X = scale * self.shape[0]
        Y = scale * self.shape[1]
        v1 = dot(self.T, array([+X, +Y, 0., 1.]))[:3]
        v2 = dot(self.T, array([+X, -Y, 0., 1.]))[:3]
        v3 = dot(self.T, array([-X, -Y, 0., 1.]))[:3]
        v4 = dot(self.T, array([-X, +Y, 0., 1.]))[:3]
        return [v1, v2, v3, v4]
```

**Comment by stephane-caron** [comment]
Hi @Saeed-Mansouri, the function that you are quoting gives the coordinates of the vertices (not the inequality vectors) of the contact area in the world frame. It applies to any contact position and orientation.

Note that ``horizontal_walking.py`` is a [tutorial](https://scaron.info/teaching/prototyping-a-walking-pattern-generator.html) example, not a complete walking pattern generator. In particular, to make the code simpler it decouples MPC along the x- and y-axis (variables ``x_mpc`` and ``y_mpc``) which is valid for walking forward but not suitable for walking while turning. The general version without this decoupling is basically the one you will find in the LIPM walking controller.

**Comment by stephane-caron** [comment]
Actually the tutorial did not mention this simplification explicitly, so I updated it. Thank you for your feedback :), and hoping this will be helpful to others as well.
