### ISSUE TITLE
Simulators Effect in IK

### ISSUE THREAD

**Issue by mohamadmahdavian** [stephane-caron/pymanoid#32]
Hi Dr.Caron

I have generated many motions with pymanoid and I am sending you some results of it. First of all, please take a look at the attached figures. 
![Screenshot from 2019-10-15 16-30-30](https://user-images.githubusercontent.com/32945083/67047879-06486f00-f0e8-11e9-83b8-559a01e7bec1.png)
![Screenshot from 2019-10-15 16-30-25](https://user-images.githubusercontent.com/32945083/67047881-06486f00-f0e8-11e9-9516-f40f4442308b.png)

The figures show the trajectory of MPC generated COP vs ZMP of the robot in x and y direction based on time. The blue line is the ZMP which is noisy and I have calculated it based on the angular velocity of the joints using pymanoid functions. My questions are:
1. Currently we are using openrave to get feedback from each task by simulator into the IK (for example reading current COM position, etc.) based on the simulation. The simulators similar to real robots may be noisy and this may effect the IK process . Also, while using real robots, everyone uses some filtering to reduce the noise, but we don't have any filters in pymanoid. I wanted to know your idea about this problem. Can a simulator cause noises as what we see in the figure? 

2. Currently pymanoid's IK is trying to stabilize the motion of the robot in the simulation. I want to test the results of IK (calculated joint angles) from pymanoid on the real robot. How is it possible to solve IK algorithm without getting feedback from simulator in order to reduce noises?

Thank You

**Comment by stephane-caron** [comment]
Hi @mohamadmahdavian, to compute the ZMP you should be providing joint accelerations as ``qdd`` argument to ``compute_zmp()``. I guess you are computing them by finite difference of joint velocities, which is where you might be getting these spikes from.

> I want to test the results of IK (calculated joint angles) from pymanoid on the real robot. How is it possible to solve IK algorithm without getting feedback from simulator in order to reduce noises?

What you are observing here is the output of the inverse kinematics (remember that [pymanoid does not perform forward dynamics](https://github.com/stephane-caron/pymanoid/wiki/Frequently-Asked-Questions#does-pymanoid-include-a-forward-dynamics-simulator)). The ZMP spikes show that the solution produced by your IK tasks is not smooth enough at the second order of derivation. 

You can apply a low-pass filter to smooth these, at the cost of introducing some delay, but this would only change the plots without affecting the motion of your robot. The principled way to smooth the motion of your robot without delay is to introduce a task for it in your IK. Here are two solutions you can try:

- Implement a ``MinJerkTask`` similar to the [MinAccelTask](https://scaron.info/doc/pymanoid/inverse-kinematics.html#pymanoid.tasks.MinAccelTask) but minimizing variations of the acceleration (similar to what the [PendulumModeTask](https://scaron.info/doc/pymanoid/inverse-kinematics.html#pymanoid.tasks.PendulumModeTask) does).
- Implement a ``ZMPTask`` similar to the [COMAccelTask](https://scaron.info/doc/pymanoid/inverse-kinematics.html#pymanoid.tasks.COMAccelTask) to make your ZMPs track the reference better.

This being said, if you can experiment maybe you can already try the simple solution (smoothing acceleration trajectories by low-pass filtering) and see how it goes on the real robot. Maybe ensuring a smooth and delay-less second-order is not your top problem in practice :wink:

**Comment by mohamadmahdavian** [comment]
Thank you for your respond Dr.Caron. Adding ZMPTask has been something that we wanted to do for a long time. Because honestly motions generated in pymanoid look good in the openrave simulation. But when we go higher than 0.1km/h speed, the robot gets unbalanced. We saw this problem in resulted ZMP results and also I imported robot and pymanoid motion generated into choreonoid and robot falls down. Basically, motion generated for COM makes sure that COP in inside support polygon. But after solving IK even though real COM of the robot is following COM generated by MPC, but ZMP gets out of support polygon. But our problem for adding ZMP task is that we need to solve IK in acceleration level to have ZMP and follow a referenced ZMP. Is this correct?

**Comment by stephane-caron** [comment]
No really, if you look at the [COMAccelTask](https://scaron.info/doc/pymanoid/inverse-kinematics.html#pymanoid.tasks.COMAccelTask) for instance, it regulates the COM acceleration even though you have a velocity-level IK.

The trick is that, instead of solving ``J * qdd = x - qd.T * H * qd``, you perform a Taylor expansion and compute the equivalent velocity for your velocity-level IK. See [this note](https://scaron.info/doc/pymanoid/inverse-kinematics.html#pymanoid.tasks.PendulumModeTask) for details.
