### ISSUE TITLE
[Question] omega2 vs lambda in pendulum_stabilization.py

### ISSUE THREAD

**Issue by junhyeokahn** [stephane-caron/pymanoid#33]
Hello,
Thanks for your efforts maintaining this repository :)

I have a quick question while looking at your example code ```pendulum_stabilization.py```.
In the function ```on_tick```, why do you use ```self.omega2```(initial leg stiffness coefficient) for [gravity inertial force](https://github.com/stephane-caron/pymanoid/blob/4c6e7811b5aca973d527cc377002e04c60d890b1/examples/pendulum_stabilization.py#L92), but use ```lambda_``` for [forward dynamics](https://github.com/stephane-caron/pymanoid/blob/4c6e7811b5aca973d527cc377002e04c60d890b1/examples/pendulum_stabilization.py#L97)?
I might not understand the difference between omega and lambda.

**Comment by stephane-caron** [comment]
Hi @junhyeokahn,

**Short answer:** these two constants correspond to two different parameterizations of the contact wrench, described as _CoP-based inverted pendulum_ and _floating-base inverted pendulum_ in [Section II.B of this manuscript](https://hal.archives-ouvertes.fr/hal-01481052/document).

**Longer answer:** we can interpret ``omega`` as a normalized stiffness between the CoM and VRP [(Englsberger et al., 2015)](https://doi.org/10.1109/TRO.2015.2405592), while ``lambda`` corresponds to the virtual leg stiffness between the CoM and ZMP. The reason why the mapping is nonlinear is that the ZMP is constrained to lie on the contact surface, while the CoM can move in 3D. If you are curious about studying further the relationship between ``lambda`` and ``omega``, you will find that they are [related by a Riccati equation](https://hal.archives-ouvertes.fr/hal-01689331/document).
