### ISSUE TITLE
Multi-contact area with opposite orientation

### ISSUE THREAD

**Issue by wyqsnddd** [stephane-caron/pymanoid#35]
Hi Stephane! 

As you know, I tried to implement the C++ version of the `Multi-contact ZMP Area`(**mc-zmp-area**) since recently. Both my c++ implementation and `pymanoid` generates  similar **mc-zmp-area** in the end. However both of them have with opposite orientation than the one we used last September. Here is a link to the [video](https://seafile.lirmm.fr/f/205b27957328482db55c/)  

This is the result I obtained with `pymanoid`: 

![pymanoid-mc-zmp](https://user-images.githubusercontent.com/6009684/72731729-8e7d5b00-3b94-11ea-8c94-140eb852e385.png)

except the robot is not correctly visualized (I don't know if this is a problem related to the IK solver, but that is another issue. ).

Could you please give me some hints why and how I can improve the code  to obtain the same `mc-zmp-area` you obtained before? 

![image](https://user-images.githubusercontent.com/6009684/72732792-cb4a5180-3b96-11ea-97d9-4eea8361c057.png)

**Comment by wyqsnddd** [comment]
By the way, I forked `pymanoid` at: git@github.com:wyqsnddd/pymanoid.git

If you want, you can `git clone -b devel-grasp-matrix git@github.com:wyqsnddd/pymanoid.git` .

Then go the the folder `pymanoid/examples/contact_stability` and run: 
```sh
python zmp_support_area.py --stance=stances/hrp4-triple-pose-middle.json --robot=hrp4
```

**Comment by stephane-caron** [comment]
Hi Yuquan,

> This is very confusing thus I input the same configuration to pymanoid. Not surprisingly, I obtained a similar result:

By configuration I'm assuming you mean the _stance_ (CoM position and contact poses) from which the ZMP area is computed. Can you post the numerical values of this stance?

**Comment by wyqsnddd** [comment]
Hi @stephane-caron ,

Yes, of course. I used the following `json` file and `hrp4.dae`. 

```json
{
    "com": {
        "pos": [0.0139622, 0.000222544, 0.780762],
        "mass": 38.0255
    },
    "left_foot": {
        "shape": [0.12, 0.065],
        "friction": 0.7,
        "pose": [ 0.000204064, 0.000385415, -0.00130263, 0.999999, 0.0177203,  0.0796454, 0.00105071
   ],
        "robot_link": 18
    },
    "right_foot": {
        "shape": [0.12, 0.065],
        "friction": 0.7,
        "pose": [ -0.000260182, -5.22322e-05, 0.000994766, 0.999999, 0.0191126, -0.0797968, 0.00105856
   ],
        "robot_link": 9
    },
    "right_hand": {
        "shape": [0.02, 0.04],
        "friction": 0.7,
        "pose": [ -0.463525, -0.503531, 0.50008, 0.530585, 0.274172, -0.344252, 1.03707
   ],
        "robot_link": 33
    }
}
```

By the way, I also implemented the 'multi-contact CoM static equilibrium area'. In this case, it works fine. My c++ implementation returns a similar result as `pymanoid`.

**Comment by wyqsnddd** [comment]
Using the following `triple-contact` for the `hrp4`, I obtained a similar figure. Basically the `mc-zmp-area` pointing to the same direction as the hand contact normal direction. 

```json
{
    "com": {
        "pos": [0.3, 0.04, 0.75],
        "mass": 62.0
    },
    "left_foot": {
        "shape": [0.12, 0.065],
        "friction": 0.5,
        "pos": [
            0.57785779237747192,
            0.38709041476249695,
            0.10231213271617889
        ],
        "robot_link": 20,
        "rpy": [
            0.47008350104274976,
            5.3997125596541066e-08,
            1.2930581213820404e-08
        ]
    },
    "right_hand": {
        "shape": [0.12, 0.065],
        "friction": 0.5,
        "pos": [
            0.65435177087783813,
            0.39171969890594482,
            1.026335597038269
        ],
        "robot_link": 33,
        "rpy": [
            1.3381710676315686,
            -0.23305234353606685,
            -0.77264784963182753
        ]
    },
    "right_foot": {
        "shape": [0.12, 0.065],
        "friction": 0.5,
        "pos": [
            -4.1245326087846479e-07,
            -0.31870916485786438,
            0.057613462209701538
        ],
        "robot_link": 13,
        "rpy": [
            -0.71244569943322367,
            0.0017363430578432853,
            0.00012478226610206157
        ]
    }
}
```

![triple-hrp4](https://user-images.githubusercontent.com/6009684/74093209-5a2ff700-4acf-11ea-9c31-e70d416604bf.png)

**Comment by wyqsnddd** [comment]
Well, please let me reformulate the question. Both **pymanoid** and my **c++** implementation have the same result. But the generated ZMP area has an opposite orientation than the one we used before. 

Here is a [video](https://seafile.lirmm.fr/f/2e6cb884ec9f40619e39/) to the **realtime updated areas**.

**Comment by stephane-caron** [comment]
I tried your triple contact stance and your result seems correct:

![image](https://user-images.githubusercontent.com/1189580/74612762-a7801a00-5108-11ea-802d-4ccc43a117e3.png)

In this case it is expected that the multi-contact ZMP support area points in the direction of the hand surface normal, because we are taking the area **above** the CoM. If we take the area below the CoM (e.g. setting ``z_polygon = 0.`` in the example), the area grows in the opposite direction:

![image](https://user-images.githubusercontent.com/1189580/74612846-91bf2480-5109-11ea-9714-c8aeeda22118.png)

This is the behavior described around [Fig. 7 in the paper](https://hal.archives-ouvertes.fr/hal-02108589/document).

**Comment by wyqsnddd** [comment]
@stephane-caron Thank you very much for the reply! It is clear to me now. This is great!
