### ISSUE TITLE
NAO robot example

### ISSUE THREAD

**Issue by wbadry** [stephane-caron/pymanoid#36]
Hello,
I have three questions:

- Is it possible to have a NAO robot walking demo?
- Is there a mean to use pymanoid with webots? It is a free robotics software and I don't know how to use pymanoid to control NAO robot locomotion. I am looking for an example on it if someone has time to show how to integrate it with webots. This would be a breakthrough since it would allow modeling on Windows machines.

Thank you so much.

**Comment by stephane-caron** [comment]
I have never seen the NAO model in OpenRAVE, but if you have it in URDF format you could try to [convert it to COLLADA 1.5 using these instructions](https://scaron.info/teaching/converting-robot-models-to-openrave.html).

Regarding Windows, pymanoid is based on OpenRAVE, which AFAIK does not run on Windows. It would take a significant rewrite of the project to make it work with Webots.

It seems pymanoid is not exactly what you're looking for here, but I hope these comments still help in some way.
