### ISSUE TITLE
How to save and plot knee angle data

### ISSUE THREAD

**Issue by tkmaiti** [stephane-caron/pymanoid#37]
Dear Dr. Stephane,

I am simulating horizontal_walking.py in pymanoid/examples/.
Want to save and plot knee angle data during simulation.

Can you please suggest me how to do it.

Thank you very much.

**Comment by stephane-caron** [comment]
Sure, you can make a small process for this:
```python
class KneeAngleRecorder(pymanoid.Process):

    def __init__(self):
        super(KneeAngleRecorder, self).__init__()  # necessary
        self.left_knee_angles = []
        self.right_knee_angles = []
        self.times = []

    def on_tick(self, sim):
        self.left_knee_angles.append(robot.q[robot.left_knee])
        self.right_knee_angles.append(robot.q[robot.right_knee])
        self.times.append(sim.time)
```
Schedule it in the simulation at the end of the script, before the call to ``start_walking()``:
```python
recorder = KneeAngleRecorder()
sim.schedule(recorder)
start_walking()  # comment this out to start walking manually
```
You can then read and plot the data at any time. For example:
```python
import pylab
pylab.ion()
pylab.plot(recorder.times, recorder.left_knee_angles)
pylab.plot(recorder.times, recorder.right_knee_angles)
pylab.grid(True)
```
gives something like this:

<img src="https://user-images.githubusercontent.com/1189580/95015228-1c7a7280-064c-11eb-9ba6-e61c0ff74e48.png" width="400">

I added this example to the doc [here](https://scaron.info/doc/pymanoid/simulation-environment.html#making-a-new-process). Hoping it helps!

**Comment by tkmaiti** [comment]
Dear Dr. Stephane,

Thank you very much. It is working fine.

If I want plot angular velocity and angular acceleration I may need to call robot.qd[robot.left_knee] and robot.qdd[robot.left_knee], respectively.

Thank you again.

**Comment by stephane-caron** [comment]
Yes, `robot.qd` will work. Note that `robot.qdd` will not work here since pymanoid's IK is velocity-based: it includes [acceleration bounds](https://scaron.info/doc/pymanoid/inverse-kinematics.html#acceleration-limits) in its formulation, but does not save  accelerations themselves in `robot.qdd`. We can compute joint accelerations _a posteriori_ by finite differences:
```python
left_knee_accelerations = numpy.diff(recorder.left_knee_velocities) / sim.dt
```

**Comment by tkmaiti** [comment]
Stephane-san, Thank you again. You can close this is issue.
