### ISSUE TITLE
How to obtain and save Joint Torque 

### ISSUE THREAD

**Issue by tkmaiti** [stephane-caron/pymanoid#38]
Dear Dr. Stephane,

I want to obtain and save joint torque data during simulation.
Can you please suggest me how to do it.

I want to use the following input file.
 pymanoid/examples/horizontal_walking.py

Thank you very much.

**Comment by stephane-caron** [comment]
Sure, you can use [inverse dynamics](https://scaron.info/doc/pymanoid/forward-kinematics.html#pymanoid.robot.Robot.compute_inverse_dynamics) for that. It is called like this:
```python
    tm, tc, tg = self.robot.compute_inverse_dynamics(qdd)
    tau = tm + tc + tg
```
Note that `tau` includes both actuated joint torques and unactuated generalized forces on the floating base (last 6 DOFs). We can project on actuated joint torques by `tau[:-6]`.

I've added a [`JointRecorder`](https://github.com/stephane-caron/pymanoid/blob/5a817b0910f2db8eed64218a97e21905f08562d2/pymanoid/proc.py#L137) process that you can look at for reference. In the horizontal walking example it produces plots like this:

![image](https://user-images.githubusercontent.com/1189580/95683341-f96f3600-0bea-11eb-9f03-f7089159a8f8.png)

To get this particular plot I modified the example as follows:

```python
+    recorder = pymanoid.JointRecorder(robot)
+    sim.schedule_extra(recorder)
-    sim.start()
+    # sim.start()  # let's step the simulation below
 
     def start_walking():
         fsm.start_walking = True
 
     start_walking()  # comment this out to start walking manually
+    sim.step(240)
+    import pylab
+    pylab.ion()
+    recorder.plot(robot.left_leg + robot.right_leg)
```

**Comment by tkmaiti** [comment]
It is working perfectly. Thank you very much.
