### ISSUE TITLE
Numerical Error with `ContactSet.find_supporting_wrenches` function

### ISSUE THREAD

**Issue by hungpham2511** [stephane-caron/pymanoid#5]
Hi,

As the title mentioned, I am trying to use `ContactSet.find_supporting_wrenches` to 
compute the actual contact forces. I use the function with a total wrench `w` which I 
verified to satisfies `Fw <= 0`, where `F=contact_set.compute_wrench_face()`.  However,
I kept having `ValueError constraints are inconsistent, no solution` exception from quadprog.
 
Note that the wrench `w` is most likely an extremal wrench.

I did another experiment in which I give to the `find_supporting_wrenches` function the columns
of the span matrix given by `contact_set.wrench_span`, however, the exception appears all the 
same.

Is it possible that there are some sources of numerical/rounding errors within the function that
cause this problem?

**Comment by hungpham2511** [comment]
I made some further investigation and think the cause is with `Contact.wrench_face` and `Contact.wrench_span` initialization.

When I run the following test script, the assertions failed. 
``` python
        contact_set = single_contact
        contact = single_contact.contacts[0]

        S1 = contact.wrench_rays
        F1 = contact.wrench_face
        for si in S1:
            err = np.dot(F1, si)
            assert np.all(err <= 0), "Positive entries"
```

**Comment by stephane-caron** [comment]
Woot! Thanks for finding that one :-)

The bug dwelled in the ``vertices`` field, which had a legacy offset of ``-contact_slab_thickness``. Checking your test now:

```
In [4]: dot(contact.wrench_face, contact.wrench_span).max()
Out[4]: 1.3877787807814457e-17
```

Note that you should avoid comparing floating-point numbers to a sharp 0. For instance you can do ``np.all(err <= 1e-10)`` rather than ``<= 0``.

**Comment by hungpham2511** [comment]
That's a quick fix! 

However, my tests for `find_supporting_wrenches` function still do not work.  See below for the code (I used `pytest` for this script so it won't run using normal `python ...`).

I think the numerical error kind of mess with `quadprog` somehow. 

``` python
class TestContactSet(object):
    """ 
    """
    def test_wrench_face_wrench_span(self, double_contact):
        contact_set = double_contact
        p = np.zeros(3)
        F = contact_set.compute_wrench_face(p)
        S = contact_set.compute_wrench_span(p)

        # Simple assertion
        for i in range(S.shape[1]):
            v = np.dot(F, S[:, i])
            assert np.all(v <= TINY)

    def test_supporting_wrench_from_span(self, double_contact):
        """ Compute the supporting wrenches from wrench_ray.
        """
        contact_set = double_contact
        p = np.zeros(3)
        S = contact_set.compute_wrench_span(p)

        #
        for i in range(S.shape[1]):
            si = S[:, i]
            res = contact_set.find_supporting_wrenches(si, p)
            assert res is not None
            # ValueError Exception raised at this point.
```

**Comment by stephane-caron** [comment]
OK, I was able to reproduce your results on my machine:
- Your first test runs fine for me with ``TINY=1e-7``.
- Indeed ``quadprog`` fails for some extremal wrenches.

I guess this is related to the Goldfarb-Idnani dual algorithm. For extremal cases, it works better with CVXOPT, which implements a primal-dual method. I will add an option to select the solver in ``find_supporting_wrenches()``.

**Comment by stephane-caron** [comment]
OK, your test should work now with CVXOPT. I checked that the following works on my machine (in hand-made settings that fail with quadprog):

```python
        for i in range(S.shape[1]):
            si = S[:, i]
            res = contact_set.find_supporting_wrenches(si, p, solver='cvxopt')
            assert res is not None
```

I guess the good practice is too use quadprog for speed but CVXOPT when extremal wrenches are expected. This is explained in the docstring now.

Thanks a lot for your feedback!

**Comment by hungpham2511** [comment]
Glad you find them helpful!
